spring.application.name=ai
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:edupath_ai_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:123}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.requires=true
jwt.secret=${JWT_SECRET:0edddeea31fc1daebc1a6814311a5c2a9bc6e860b7e6a8d79428d0e98d055306}
jwt.expiration=604800000
jwt.refresh-expiration=604800000
openrouter.api.key=${OPENROUTER_API_KEY:your_api_key_here}
openrouter.api.url=https://openrouter.ai/api/v1/chat/completions
